version: "3.9"
services:
  backend:
    image: node
    container_name: dockerbackend
    ports:
      - 3000:3000
    build: ./backend
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    entrypoint:
      - yarn
      - run
      - start

  frontend:
    image: node
    container_name: dockerfrontend
    ports:
      - 3001:3001
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    entrypoint:
      - yarn
      - run
      - dev
      
