version: '3.8'

services:
  jupyter:
    build: ./
    ports:
      - 8888:8888
    entrypoint:
      - jupyter
      - notebook
      - --allow-root
      - --ip
      - 0.0.0.0
      - --notebook-dir
      - /data_dir
    volumes:
      - jupyter_data:/data_dir

volumes:
  jupyter_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jarusll/source
      
