version: '3.8'

services:
  jupyter:
    build: ./
    entrypoint:
      - jupyter
      - lab
      - --allow-root
      - --ip
      - 0.0.0.0
      - --port
      - "8000"
      - --notebook-dir
      - /data_dir
    volumes:
      - jupyter_data:/data_dir
      - jupyter_config:/root/.jupyter
  caddy:
    image: caddy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"

volumes:
  jupyter_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jarusll/jupyter
  jupyter_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jarusll/.jupyter
      
